<?php

function otp_options_init()
{
    register_setting(
        'otp_options_group',
        'otp_issuing_page'
    );

    register_setting(
        'otp_options_group',
        'otp_protected_pages'
    );

    register_setting(
        'otp_options_group',
        'otp_protected_post_types'
    );

    register_setting(
        'otp_options_group',
        'otp_first_protected_page'
    );

    register_setting(
        'otp_options_group',
        'otp_code_expiry_length'
    );

    register_setting(
        'otp_options_group',
        'otp_session_expiry_length'
    );

    register_setting(
        'otp_options_group',
        'otp_db_table_suffix'
    );

    register_setting(
        'otp_options_group',
        'otp_issuing_page_slug'
    );

    register_setting(
        'otp_options_group',
        'otp_success_page_slug'
    );

    register_setting(
        'otp_options_group',
        'otp_dev_mode'
    );

    register_setting(
        'otp_options_group',
        'otp_email_subject_line'
    );

    register_setting(
        'otp_options_group',
        'otp_email_replyto_address'
    );

    register_setting(
        'otp_options_group',
        'otp_allowed_email_domains'
    );

    register_setting(
        'otp_options_group',
        'otp_recaptcha_enabled'
    );

    register_setting(
        'otp_options_group',
        'otp_recaptcha_site_key'
    );

    register_setting(
        'otp_options_group',
        'otp_recaptcha_secret_key'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_host'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_port'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_encryption_secure'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_user'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_password'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_from_address'
    );

    register_setting(
        'otp_options_group',
        'otp_smtp_from_name'
    );

    register_setting(
        'otp_options_group',
        'otp_encryption_server_secret'
    );

}

function otp_options_page()
{
    add_menu_page(
		'OTP Options',
		'OTP Options',
		'manage_options',
		'otp_settings_page',
		'render_otp_options'
	);
}

function render_otp_options()
{
?>
    <?php 
        $allowed_email_domains = get_option('otp_allowed_email_domains', array());
        if (empty($allowed_email_domains)) {
            $allowed_email_domains = array();
        }
    ?>
    <div class="wrap">
        <h1>OTP Plugin Options</h1>
        <h2>Reset the plugin by deactivating and then reactivating</h2>
        <p>The settings of the following - the WP pages generated by the plugin, the DB table created by the plugin; and the Cron jobs associated with clearing the DB -
            Are only set when the plugin is activated. That means that if you would like to make changes to any of these areas, 
            please deactivate the plugin, make your changes and the reactivate the plugin to see your change.
        </p>
        <h2>Cookie Warning</h2>
        <p>In order for this plugin to function properly on your website, the cookie `PHPSESSID` needs to be a whitelisted or 'strictly necessary' cookie. 
            This is only necessary if your site has a plugin that handles/cleans cookies. The logging in feature will not work if this cookie is not allowed to be used
        </p>
        <h2>Allowed Email Domains</h2>
        <p>Example format: "gmail.com", don't include @ sign. Not intended to be open to everyone. Could create large demand on your email service if not taken care of well. 
            Future work to create other ways to manage allowed users
        </p>
        <h2>HMAC Encryption Server Secret</h2>
        <p>This must be a randomly generated string of numbers and letters at least 32 characters long and no longer than 64 characters</p>
        
        <form method="post" action="options.php">
            <?php settings_fields('otp_options_group'); ?>
            <table class="form-table">
                <tr valign="top">
                    <th scope="row">Choose protected pages</th>
                    <td>
                        <select multiple name="otp_protected_pages[]">
                            <?php
                            $selected_protected_post_ids = array_column(get_pages(array('include' => get_option('otp_protected_pages'))), 'ID');
                            if ($pages = get_pages()) {
                                foreach ($pages as $page) {
                                    $selected = in_array($page->ID, $selected_protected_post_ids) ? ' selected ' : '';
                                    echo '<option value="' . $page->ID . '" ' . $selected  . ' >' . $page->post_title . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Choose protected post types</th>
                    <td>
                        <select multiple name="otp_protected_post_types[]">
                            <?php
                            global $wp_post_types;
                            $selected_protected_post_types = get_option('otp_protected_post_types', array());
                            empty($selected_protected_post_types) && $selected_protected_post_types = array();
                            if ($wp_post_types) {
                                foreach ($wp_post_types as $post_type) {
                                    $selected = in_array($post_type->name, $selected_protected_post_types) ? ' selected ' : '';
                                    echo '<option value="' . $post_type->name . '" ' . $selected . ' >' . $post_type->label . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Choose protected landing page (MUST be included in the protected pages above)</th>
                    <td>
                        <select name="otp_first_protected_page">
                            <?php
                            $selected_first_protected_page = get_pages(array('include' => get_option('otp_first_protected_page')))[0]->post_title;
                            if ($pages = get_pages()) {
                                foreach ($pages as $page) {
                                    $selected = $page->post_title === $selected_first_protected_page ? ' selected ' : '';
                                    echo '<option value="' . $page->ID . '" ' . $selected  . ' >' . $page->post_title . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Choose code expiry length (minutes)</th>
                    <td>
                        <input name="otp_code_expiry_length" type="number" value="<?php echo get_option('otp_code_expiry_length', 10) ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Choose session expiry length (minutes)</th>
                    <td>
                        <input name="otp_session_expiry_length" type="number" value="<?php echo get_option('otp_session_expiry_length', 300) ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Choose DB table name suffix</th>
                    <td>
                        <input name="otp_db_table_suffix" type="text" value="<?php echo get_option('otp_db_table_suffix', 'otp_details') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Confirmation email subject line</th>
                    <td>
                        <input name="otp_email_subject_line" type="text" value="<?php echo get_option('otp_email_subject_line') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP Host</th>
                    <td>
                        <input name="otp_smtp_host" type="text" value="<?php echo get_option('otp_smtp_host', 'smtp.gmail.com') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP Port</th>
                    <td>
                        <input name="otp_smtp_port" type="number" value="<?php echo get_option('otp_smtp_port', 465) ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP Encryption</th>
                    <td>
                        <input name="otp_smtp_encryption_secure" type="text" value="<?php echo get_option('otp_smtp_encryption_secure', 'ssl') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP User Email</th>
                    <td>
                        <input name="otp_smtp_user" type="text" value="<?php echo get_option('otp_smtp_user') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP Password</th>
                    <td>
                        <input name="otp_smtp_password" type="text" value="<?php echo get_option('otp_smtp_password') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP From email address</th>
                    <td>
                        <input name="otp_smtp_from_address" type="text" value="<?php echo get_option('otp_smtp_from_address') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">SMTP From name</th>
                    <td>
                        <input name="otp_smtp_from_name" type="text" value="<?php echo get_option('otp_smtp_from_name') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Confirmation email replyto address</th>
                    <td>
                        <input name="otp_email_replyto_address" type="email" value="<?php echo get_option('otp_email_replyto_address') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Allowed email domains</th>
                    <td>
                        <input id="add-allowed-email-input" type="text" />
                        <button id="add-allowed-email-button" type="button" onclick>ADD</button>
                        <div>
                            <ul id="allowed-email-list">
                            <?php foreach ($allowed_email_domains as $key => $value) : ?>
                                <li>
                                    <input data-index="<?php echo $key ?>" name='otp_allowed_email_domains[]' value="<?php echo $value ?>"/>
                                    <button type="button" data-index="<?php echo $key ?>">DELETE</button>
                                </li>
                            <?php endforeach ?>
                            </ul>
                            <script>
                                const buttons = document.querySelectorAll('button[data-index]');
                                buttons.forEach((button) => {
                                    button.addEventListener('click', e => e.target.parentElement.remove());
                                });
                            </script>
                        </div>
                    </td>
                    <script>
                        document.getElementById('add-allowed-email-button').addEventListener('click', (event) => {
                            const newIndex = document.querySelectorAll('input[data-index]').length;

                            const newAllowedEmail = document.getElementById('add-allowed-email-input').value;
                            const container = document.getElementById('allowed-email-list');
                            const li = document.createElement('li');

                            const input = document.createElement('input');
                            input.dataset.index = newIndex;
                            input.value = newAllowedEmail;
                            input.name = 'otp_allowed_email_domains[]';

                            const deleteButton = document.createElement('button');
                            deleteButton.type = "button";
                            deleteButton.innerHTML = "DELETE";
                            deleteButton.addEventListener('click', e => e.target.parentElement.remove());
                            li.append(input);
                            li.append(deleteButton);
                            container.prepend(li);
                            document.getElementById('add-allowed-email-input').value = '';
                        })
                    </script>
                </tr>
                <tr valign="top">
                    <th scope="row">Enable ReCaptcha</th>
                    <td>
                        <input name="otp_recaptcha_enabled" type="checkbox" value="otp_recaptcha_enabled" <?php echo get_option('otp_recaptcha_enabled', '') === "otp_recaptcha_enabled" ? "checked" : ""; ?> />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">ReCaptcha site key</th>
                    <td>
                        <input name="otp_recaptcha_site_key" type="text" value="<?php echo get_option('otp_recaptcha_site_key') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">ReCaptcha secret key</th>
                    <td>
                        <input name="otp_recaptcha_secret_key" type="text" value="<?php echo get_option('otp_recaptcha_secret_key') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">HMAC Encryption server secret</th>
                    <td>
                        <input name="otp_encryption_server_secret" type="text" value="<?php echo get_option('otp_encryption_server_secret') ?>" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Developer mode</th>
                    <td>
                        <input name="otp_dev_mode" type="checkbox" value="otp_dev_mode" <?php echo get_option('otp_dev_mode', '') === "otp_dev_mode" ? "checked" : ""; ?> />
                    </td>
                </tr>
            </table>
            <p class="submit">
                <input type="submit" class="button-primary" value="<?php _e('Save Changes') ?>" />
            </p>
        </form>
    </div>
<?php
}

?>